name: Publish to NPM

on:
  push:
    branches:
      - main # Veya senin ana branch adın neyse (örn: master)
    tags:
      - 'v*' # Sadece v1.0.1 gibi tag'ler pushlandığında çalışır

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Publish to NPM
        run: |
          cd dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}